#!/usr/bin/env python3
"""Assemble frontend/shared/vendor/solid-bundle.js from the three vendored ESM files.

solid-js / solid-js/web / hyperscript h() are raw source copies: strip their
import/export statements, splice them into one IIFE, and expose everything as the
window.MudraSolid global — so MV3 content scripts (no ESM) and the panel (no
bundler) share a single vendored artifact. Re-run after upgrading the vendor
copies; the bundle is committed, this build step is not part of serving.
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
V = ROOT / "frontend" / "shared" / "vendor"

core = (V / "solid.js").read_text()
web = (V / "solid-web.js").read_text()
h_src = (V / "solid-h.js").read_text()


def strip_export(src: str) -> tuple[list[tuple[str, str]], str]:
    """Remove the trailing `export {...};` and return (local, public) name pairs."""
    m = re.search(r"^export \{([^}]+)\};", src, re.M)
    items = []
    for item in m.group(1).split(","):
        item = item.strip()
        if " as " in item:
            local, public = (s.strip() for s in item.split(" as "))
        else:
            local = public = item
        items.append((local, public))
    return items, src[: m.start()] + src[m.end():]


core_pairs, core = strip_export(core)
web_pairs, web = strip_export(web)

# solid-web re-exports core bindings (`export { X } from 'solid-js'`) and imports
# others; with both in one scope those statements reduce to nothing.
web = web.replace(
    "import { createMemo, sharedConfig, createRenderEffect, createRoot, untrack, "
    "splitProps, getOwner, createEffect, runWithOwner, createSignal, onCleanup, "
    "enableHydration } from 'solid-js';\n", "")
web = web.replace(
    "export { ErrorBoundary, For, Index, Match, Show, Suspense, SuspenseList, Switch, "
    "createComponent, createRenderEffect as effect, getOwner, mergeProps, untrack } "
    "from 'solid-js';\n", "")
h_src = h_src.replace(
    "import { SVGElements, dynamicProperty, createComponent, insert, assign, spread } "
    "from 'solid-js/web';\n", "")
h_src = h_src.replace("export { h as default };\n", "")

# Existence-check every local binding that survives into the bundle scope.
scope = core + web
missing = sorted({
    local for local, _ in core_pairs + web_pairs
    if not re.search(rf"\b(?:var|const|let|function|class)\s+{re.escape(local)}\b", scope)
})
assert not missing, f"bundle references undefined locals: {missing}"

pairs: dict[str, str] = {}
for local, public in core_pairs + web_pairs:
    pairs[public] = local  # web's re-export of core names resolves to the same binding

lines = ",\n".join(f"  {public}: {local}" for public, local in sorted(pairs.items()))
bundle = f"""// Generated by tools/make_solid_bundle.py — do not edit by hand.
// Vendored: solid-js + solid-js/web + hyperscript h(), exposed as window.MudraSolid.
(function () {{
"use strict";
{core}
{web}
{h_src}
const MudraSolid = {{
{lines},
  h,
  render: (code, el) => {{
    const owner = createRoot(() => insert(el, code()));
    return owner;
  }},
}};
window.MudraSolid = MudraSolid;
}})();
"""
(V / "solid-bundle.js").write_text(bundle)
print(f"solid-bundle.js written: {len(pairs)} exports + h/render, "
      f"{len(bundle.splitlines())} lines")
